        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:37 2025
        MODULE A_INPUT_mod
          INTERFACE 
            SUBROUTINE A_INPUT
            END SUBROUTINE A_INPUT
          END INTERFACE 
        END MODULE A_INPUT_mod
