        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE AA_MAKE_MATRIX_mod
          INTERFACE 
            SUBROUTINE AA_MAKE_MATRIX
            END SUBROUTINE AA_MAKE_MATRIX
          END INTERFACE 
        END MODULE AA_MAKE_MATRIX_mod
