        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:36 2025
        MODULE B_COORDINATES_mod
          INTERFACE 
            SUBROUTINE B_COORDINATES
            END SUBROUTINE B_COORDINATES
          END INTERFACE 
        END MODULE B_COORDINATES_mod
