        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:26 2025
        MODULE C_ROTATION_LOCAL_STRUCTURE_mod
          INTERFACE 
            SUBROUTINE C_ROTATION_LOCAL_STRUCTURE
            END SUBROUTINE C_ROTATION_LOCAL_STRUCTURE
          END INTERFACE 
        END MODULE C_ROTATION_LOCAL_STRUCTURE_mod
