        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:25 2025
        MODULE G02_ROTATION_GAMMA_mod
          INTERFACE 
            SUBROUTINE G02_ROTATION_GAMMA
            END SUBROUTINE G02_ROTATION_GAMMA
          END INTERFACE 
        END MODULE G02_ROTATION_GAMMA_mod
