        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:26 2025
        MODULE G0_ROTATION_AMAT_mod
          INTERFACE 
            SUBROUTINE G0_ROTATION_AMAT
            END SUBROUTINE G0_ROTATION_AMAT
          END INTERFACE 
        END MODULE G0_ROTATION_AMAT_mod
