        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:36 2025
        MODULE GA_MAKE_BMAT_mod
          INTERFACE 
            SUBROUTINE GA_MAKE_BMAT
            END SUBROUTINE GA_MAKE_BMAT
          END INTERFACE 
        END MODULE GA_MAKE_BMAT_mod
