        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE GB_MAKE_KMAT_mod
          INTERFACE 
            SUBROUTINE GB_MAKE_KMAT
            END SUBROUTINE GB_MAKE_KMAT
          END INTERFACE 
        END MODULE GB_MAKE_KMAT_mod
