        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE GBA_BOUNDARYCONDITION_mod
          INTERFACE 
            SUBROUTINE GBA_BOUNDARYCONDITION
            END SUBROUTINE GBA_BOUNDARYCONDITION
          END INTERFACE 
        END MODULE GBA_BOUNDARYCONDITION_mod
