        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:36 2025
        MODULE LA_MAKE_DMAT_mod
          INTERFACE 
            SUBROUTINE LA_MAKE_DMAT
            END SUBROUTINE LA_MAKE_DMAT
          END INTERFACE 
        END MODULE LA_MAKE_DMAT_mod
