        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:25 2025
        MODULE LAA_MAKE_SMAT_mod
          INTERFACE 
            SUBROUTINE LAA_MAKE_SMAT
            END SUBROUTINE LAA_MAKE_SMAT
          END INTERFACE 
        END MODULE LAA_MAKE_SMAT_mod
