        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:37 2025
        MODULE LB_MAKE_BMAT_mod
          INTERFACE 
            SUBROUTINE LB_MAKE_BMAT
            END SUBROUTINE LB_MAKE_BMAT
          END INTERFACE 
        END MODULE LB_MAKE_BMAT_mod
