        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE LC_MAKE_KMAT_mod
          INTERFACE 
            SUBROUTINE LC_MAKE_KMAT
            END SUBROUTINE LC_MAKE_KMAT
          END INTERFACE 
        END MODULE LC_MAKE_KMAT_mod
