        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 20 15:24:15 2025
        MODULE LCA_BOUNDARYCONDITION_mod
          INTERFACE 
            SUBROUTINE LCA_BOUNDARYCONDITION
            END SUBROUTINE LCA_BOUNDARYCONDITION
          END INTERFACE 
        END MODULE LCA_BOUNDARYCONDITION_mod
