        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE LE_MAKE_XMAT_mod
          INTERFACE 
            SUBROUTINE LE_MAKE_XMAT
            END SUBROUTINE LE_MAKE_XMAT
          END INTERFACE 
        END MODULE LE_MAKE_XMAT_mod
