        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:36 2025
        MODULE LF_MAKE_AMAT_mod
          INTERFACE 
            SUBROUTINE LF_MAKE_AMAT
            END SUBROUTINE LF_MAKE_AMAT
          END INTERFACE 
        END MODULE LF_MAKE_AMAT_mod
