        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:36 2025
        MODULE LI_MAKE_MMAT_mod
          INTERFACE 
            SUBROUTINE LI_MAKE_MMAT
            END SUBROUTINE LI_MAKE_MMAT
          END INTERFACE 
        END MODULE LI_MAKE_MMAT_mod
