        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:34 2025
        MODULE LJ_MAKE_PSI_mod
          INTERFACE 
            SUBROUTINE LJ_MAKE_PSI
            END SUBROUTINE LJ_MAKE_PSI
          END INTERFACE 
        END MODULE LJ_MAKE_PSI_mod
