        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE LK_MAKE_GAMMA_mod
          INTERFACE 
            SUBROUTINE LK_MAKE_GAMMA
            END SUBROUTINE LK_MAKE_GAMMA
          END INTERFACE 
        END MODULE LK_MAKE_GAMMA_mod
