        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:34 2025
        MODULE MAKE_BTGAMMA_mod
          INTERFACE 
            SUBROUTINE MAKE_BTGAMMA
            END SUBROUTINE MAKE_BTGAMMA
          END INTERFACE 
        END MODULE MAKE_BTGAMMA_mod
