        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:26 2025
        MODULE MAKE_THEATA_mod
          INTERFACE 
            SUBROUTINE MAKE_THEATA
            END SUBROUTINE MAKE_THEATA
          END INTERFACE 
        END MODULE MAKE_THEATA_mod
