        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:25 2025
        MODULE MAKE_INVERSE_mod
          INTERFACE 
            SUBROUTINE MAKE_INVERSE(A,INVA,M)
              INTEGER(KIND=4), INTENT(IN) :: M
              REAL(KIND=8), INTENT(IN) :: A(M,M)
              REAL(KIND=8), INTENT(INOUT) :: INVA(M,M)
            END SUBROUTINE MAKE_INVERSE
          END INTERFACE 
        END MODULE MAKE_INVERSE_mod
