        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:26 2025
        MODULE ROTATION_G_E_TH_mod
          INTERFACE 
            SUBROUTINE ROTATION_G_E_TH
            END SUBROUTINE ROTATION_G_E_TH
          END INTERFACE 
        END MODULE ROTATION_G_E_TH_mod
