        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:08:25 2025
        MODULE ROTATION_G_SE_TH_mod
          INTERFACE 
            SUBROUTINE ROTATION_G_SE_TH
            END SUBROUTINE ROTATION_G_SE_TH
          END INTERFACE 
        END MODULE ROTATION_G_SE_TH_mod
