        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE SOLVE_THERMAL_ELASTIC_mod
          INTERFACE 
            SUBROUTINE SOLVE_THERMAL_ELASTIC
            END SUBROUTINE SOLVE_THERMAL_ELASTIC
          END INTERFACE 
        END MODULE SOLVE_THERMAL_ELASTIC_mod
