        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:36 2025
        MODULE SOLVE_STRESS_mod
          INTERFACE 
            SUBROUTINE SOLVE_STRESS
            END SUBROUTINE SOLVE_STRESS
          END INTERFACE 
        END MODULE SOLVE_STRESS_mod
