        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE SOLVE_STRAIN_mod
          INTERFACE 
            SUBROUTINE SOLVE_STRAIN
            END SUBROUTINE SOLVE_STRAIN
          END INTERFACE 
        END MODULE SOLVE_STRAIN_mod
