        !COMPILER-GENERATED INTERFACE MODULE: Wed Mar 19 15:04:35 2025
        MODULE SOLVE_DISP_mod
          INTERFACE 
            SUBROUTINE SOLVE_DISP
            END SUBROUTINE SOLVE_DISP
          END INTERFACE 
        END MODULE SOLVE_DISP_mod
